# Generated by Django 5.0.3 on 2024-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Sistema_Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
