# Generated by Django 5.0.3 on 2024-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Sistema_Biblioteca', '0002_alter_usuario_email_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('lancamento', models.DateField()),
                ('notaMedia', models.FloatField()),
            ],
        ),
    ]
