# Generated by Django 5.0.3 on 2024-04-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Sistema_Biblioteca', '0004_avaliacao_resenha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenha',
            old_name='texto',
            new_name='resenha',
        ),
    ]
