# Generated by Django 5.0.3 on 2024-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Sistema_Biblioteca', '0006_remove_livros_notamedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
