# Generated by Django 5.0.3 on 2024-04-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Sistema_Biblioteca', '0007_usuario_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=32),
        ),
    ]
